name: Pest Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  pest_tests:
    runs-on: ${{ matrix.operating-systems }}

    strategy:
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ['8.2']

    name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-systems }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, fileinfo, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Clone UnoPim Core
        run: |
          git clone https://github.com/unopim/unopim.git core

      - name: Copy Package into UnoPim
        run: |
          mkdir -p core/packages/Webkul
          cp -R packages/Webkul/Shopify core/packages/Webkul/

      - name: Install Dependencies
        working-directory: core
        run: composer install

      - name: Setup Environment
        working-directory: core
        run: |
          cp .env.example .env
          sed -i "s|^\(APP_ENV=\s*\).*$|\1testing|" .env
          sed -i "s|^\(DB_HOST=\s*\).*$|\1127.0.0.1|" .env
          sed -i "s|^\(DB_PORT=\s*\).*$|\1${{ job.services.mysql.ports['3306'] }}|" .env
          sed -i "s|^\(DB_DATABASE=\s*\).*$|\1unopim|" .env
          sed -i "s|^\(DB_USERNAME=\s*\).*$|\1root|" .env
          sed -i "s|^\(DB_PASSWORD=\s*\).*$|\1root|" .env

      - name: Dump Autoload
        working-directory: core
        run: composer dump-autoload

      - name: Install UnoPim
        working-directory: core
        run: php artisan unopim:install --skip-env-check --skip-admin-creation

      - name: Run Pest Tests
        working-directory: core
        run: vendor/bin/pest --parallel --colors=always
